### PR TITLE
Meyda 3.0

### LINKED ISSUE #86: Offline `get` method
Following our discussion – related to #85 – I think the best course of action is what @hughrawlinson suggested.

This would be an offline version of the `get` method (couldn't think of a hot name for it yet), which would behave as follows:

+ Argument no. 1 will be identical to the standard `get`, i.e. a `String` denoting the desired feature, or an `Array` of such strings. Argument no. 2 will be a Float32Array containing the signal buffer to analyze.
+ It is IMO necessary to make sure that this method can be called even while the internal SPN/AudioWorker/Paul/whatever they're going to call it is running and doing its thing.
+ The offline `get` would then:
  + Make a list of all the calculations needed to extract the specified features (this could be either the amplitude spectrum, complex spectrum, or none)
  + Perform the calculations (ideally in a separate AudioWorker, but for now it can be done on the JS thread)
  + Call the specified extractors, and pass them the signal/calculated FFT data 
  + return the output the same way as the classic `get` would
+ As a consequence, `Meyda` should be able to run without a specified AudioContext/source node

As discussed in #85 and #84 this would create a simple API for offline AFE, and also extend the functionality of a single `Meyda` object, as it could now in theory analyze two simultaneous audio streams.

### LINKED ISSUE #93: Add more windows
We should add more windowing functions such as sine, rectangular and triangular.

### PR DESCRIPTION
**Pull request by nevosegal**
This fixes #93 and also fixes the blackman window.

Fixes #86

### CODE REVIEW

**Comment by jakubfiala** [comment]
very cool! I'm afraid I don't have time to write the new tests yet, but since CI is failing without them, we probably have to do them :(

**Comment by nevosegal** [comment]
AFAIK only the MFCC is failing, which I'm planning on fixing now.

**Comment by jakubfiala** [comment]
Cool! also do you mind if we rename this PR to something that encompasses all the changes in it? 😃 just for clarity's sake.

**Comment by hughrawlinson** [comment]
Updated Issue Name to describe all changes, added `fixes` tags to the description (I think they have to go there rather than in a comment).

I think we just need to fix that test (MFCC values are wrong) and we're good to go? @nevosegal @jakubfiala anything to add?

**Pull request merged**
