### PR TITLE
Separate "extractors" export

### PR DESCRIPTION
**Pull request by jakubfiala**
This is a small change which opens up access to the internal extractor functions for processing arbitrary Float32 data.

Useful because:
+ enables offline AFE
+ enables FE on non-audio data

### CODE REVIEW

**Comment by hughrawlinson** [comment]
Just a quick note, offline AFE was already possible with OfflineAudioContext or requiring non-main files from the package, but this makes it really convenient :) Thanks! :+1:

**Comment by hughrawlinson** [comment]
Actually, maybe consider adding a test so that in the future we know immediately if for any reason this breaks?

**Comment by jakubfiala** [comment]
Indeed it was, my bad 😊 good point, might add the test later

**Comment by hughrawlinson** [comment]
Sorry to be pedantic about it, and I realize that we're not comprehensively tested as it is (when I realistically have time to do something about it I'll investigate metrics for determining testedness and work on improving those), but I think it's probably for the best to only add this once there are tests for it so that we don't slip further back on our testedness. Of course, @jakubfiala and @nevosegal should feel free to overrule me, three person open source core teams are perfect for that kind of governing :smile: 

I'm happy to write the tests myself this week assuming that you don't mind waiting a few days for this to get merged to master and published to bower and npm?

**Comment by hughrawlinson** [comment]
@jakubfiala is this still relevant after #95?

**Comment by hughrawlinson** [comment]
Everything done in this was done in v3.0.0, closing.

**Pull request closed without merging**
