### PR TITLE
V1.1

### LINKED ISSUE #71: Modularisation
Hello,

After a quick chat with @jakubfiala I mentioned that modularisation would be great for my use-case, so I thought it would be a good idea to post an issue here.

I'm a big fan of commonJS, I've been using it in many different libraries and it has worked great so far, and it allows a really nice workflow…

I've gone ahead and did some basic separations here:

https://github.com/vectorsize/meyda/tree/commonJS

to see how it works and it seems to be working perfectly!

I also did a few performance optimisations. Everything is in a commonJS branch in case u guys like it and feel like incorporating it.

That said if you decide to go for other type of modules, I think what I did is a good starting point.
Also the small optimisations in the main function still make sense.

Let me know what you think.

### PR DESCRIPTION
**Pull request by hughrawlinson**
# This is it!

:sparkles: :tada: :balloon: :birthday: :gift: :facepunch: :factory: :shipit: :panda_face: 

Meyda v1.1 is ready for `origin/master`!

## Changelog
* reorganised the project into multiple files
* rewrote files into ESNext classes (and took advantage of other ESNext features like block scope)
* added [babel](babeljs.io) as a dependency for transpilation
* added [mocha](mochajs.org) and [chai](chaijs.com) for testing
* wrote many many *many* tests, some for each of the extractors, and some overall tests
* added [jshint](jshint.com) for making sure the code style is good
* added some test coverage metric tools
* made a gulp build script with various targets *including NODE JS!*
* made a makefile which is useful
* added meyda to bower (and will do to npm as soon as this PR lands)
* configured travis-ci and codeclimate as continuous integration tools.

## HowTo
There's a lot changing in here, so I want to specifically highlight the major changes that will impact developing and using meyda.

### Building and testing
The Makefile should be used as documentation for this, and it's fairly straightforward - tl;dr: just run `make`. Make will clean the project, install dependencies, compile for node, compile and build for web, run testing, linting, and coverage. It should exit with 0. You can of course run each of those tasks individually, and you should refer to the Makefile for documentation. I would of course be happy to write up documentation specifically for this if requested.

### Including meyda
Using meyda in the web has changed *slightly*, in the way in which we instantiate. Previously, one would have instantiated meyda as follows: `var meyda = new Meyda(context, source, bufferSize);`. Now though, we pass an object containing those parameters. `var meyda = new Meyda({audioContext:context,source:source,bufferSize:bufferSize});`. This is designed to enhance future compatibility - now that we accept one object, we can always accept it. It's a common pattern among other libraries and functions.

### Developing
Primarily, the difference is that now we write extractors in separate files, and in es6 (not forgetting to add them to `featureExtractors.js`). I anticipate this will actually make it *easier* to write new extractors and to include them, and will hopefully encourage more contribution.

## What do I do right now?
If you're so inclined to help with this, first of all thanks. I put a lot of work into this, and I'd really appreciate a code review - the last thing I want is to merge this and cause issues for people using it. You can help by cloning this branch, running `make`, and using the resulting files in the `dist` folder in your projects, letting me know if you have any issues. If you're interested, it'd be great if you could read through my code and question my every move.

## Anything else?
_Let me know by replying to this PR!_

Thanks,

Hugh

Fixes #71 #70 #68 #60

### CODE REVIEW

**Comment by jakubfiala** [comment]
Just FYI, I'm watching all this, I've been on holiday for quite a while and haven't had a chance to review the changes, but generally looks great. I expect to have some time for this in August, but if you don't want to wait until then, I'm fine with you and @nevosegal releasing this. Thanks for the huge amount of work!

**Comment by hughrawlinson** [comment]
Have a great holiday @jakubfiala! :smile:

**Comment by nevosegal** [comment]
Well done @hughrawlinson! Thanks a lot for all the effort you're putting into this. I will go through the changes and reply soon.

**Comment by vectorsize** [comment]
good job guys!

**Comment by hughrawlinson** [comment]
Thanks @vectorsize, it should be much easier for us to press ahead with adding new feature extractors! Let us know if you've got a specific feature you're looking for :smile:

**Comment by vectorsize** [comment]
That's really cool @hughrawlinson , will spend some tie with the new code as soon as I have some time and let the other guys at Ircam know, unfortunately I don't work with them anymore, but still interested nonetheless!!!

**Comment by kirbysayshi** [comment]
@hughrawlinson this looks really great! I've only briefly played around with meyda, but really glad to see it heading in a modular direction.

I think you might be able to get away without using make though. Since all of the make targets are really just tasks, you could probably just use npm's scripts:

```
"scripts": {
  "lint": "jshint src test",
  "build-node": "gulp buildNode",
  "build": "npm run build-node && npm run build-web"
  ... etc
}
```

**Comment by hughrawlinson** [comment]
@kirbysayshi good point, I started using make when I was working with a company who were using it across all codebases and wanted to keep everything the same, I guess it just stuck. Feel free to submit a PR, otherwise I'll probably get around to it at some point.

**Pull request merged**
