### PR TITLE
Update to use jsfft from npm and switch build process to webpack 2

### PR DESCRIPTION
**Pull request by 2xAA**
Fixes issues #138 and #179 :)

### CODE REVIEW

**Comment by 2xAA** [comment]
Oh :(

I'll get to work haha.

**Comment by 2xAA** [comment]
Okay, so the tests fail on v4 and v5 as jsfft is still ES6 code.
However the compiled output of meyda and meyda.min.js is valid ES5.

So, yeah, this sucks haha.

**Comment by hughrawlinson** [comment]
If I remember correctly, this is the reason that we didn't upgrade to the current version on jsfft - we'd need to figure out how to compile the dependency. This is the reason that we supposedly compile meyda to es5 before putting it on npm.

**Comment by hughrawlinson** [comment]
We can solve it by adding a build step to build jsfft as es5 manually. Seems bad to mess around with dependencies like this, but I'm up for it.

**Pull request merged**
